spring.datasource.url=jdbc:sqlserver://localhost;databaseName=WalletDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=hoai
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
# --- CẤU HÌNH GỬI MAIL ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=DIEN_EMAIL_CUA_BAN_VAO_DAY
spring.mail.password=DIEN_APP_PASSWORD_16_KY_TU_VAO_DAY
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true